Lesson_10
AlenaShurakova/JavaHomeWork pull request #8
Opened 2020-09-19 11:43 UTC by AlenaShurakova

2020-09-23 15:32 UTC, RomanKashenok requested changes

2020-09-23 15:32 UTC, RomanKashenok commented on src/lesson_10/task_29/Runner.java
> +                iterator = marksList.iterator();
you can just iterate with for cycle to not to create iterator

2020-09-23 15:32 UTC, RomanKashenok commented on src/lesson_10/task_32/Runner.java
> +        while (iterator.hasNext()) {
you can iterate one time over "words" and on every word get Value from dictinary. If value is null (such key is not in the map yet) you can pass 1 there, if value exasts - just add 1 to it.

2020-09-27 12:13 UTC, AlenaShurakova commented on src/lesson_10/task_29/Runner.java
> +                iterator = marksList.iterator();
Fixed in "Lesson_10_Fixed" commit

2020-09-27 12:13 UTC, AlenaShurakova commented on src/lesson_10/task_32/Runner.java
> +        while (iterator.hasNext()) {
Fixed in "Lesson_10_Fixed" commit

2020-09-27 12:13 UTC, merged